services:
  migrate:
    # frontend の devcontainer 起動時のみ、マイグレーションをワンショット実行
    command: ["bash", "-lc", "go mod download && go run . migrate"]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
  backend:
    # frontend の devcontainer 起動時のみ、backend をアプリとして起動する
    command: ["bash", "-lc", "go mod download && go run ."]
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully


